language: node_js
node_js: 
  - "stable"
env:
   secure: "FzR8bHY4CQEnf36FDVzHm2ZpPsEr+gpkVTNBC3R5UUx087mx5XJQiTIFDXj9k9u9F29//vwM7bfznU7NedqHhhXsaqXIC8HjZhE5azMk3DahFkUW93MgvvQm5t6OTJXLTnBvZxMCB4oeeg0LgD7QagTbSvwPGtAYPvml8GKVuv/2+A3502Tiv0OYwZWKZELGbGNG6H/EIJrGWEWwjdzlfDwyMH7ac43bntJ+1p5xVm+hWiwM+mcGiRKY/ZbyeUCmQn+vEp7DKEhsESixvV+5xziYrDEVg6Fy+JhYJngmNVFhjCavZgoiHKfsEdVW4j5e9ryik53IZjB4s+LhDUxsb1RNg28MW4N6JYboC2s8Ei2rD+TxrJo0KheljrzXQtLR4s7cc9VeLSLtlSmJU8vRf2+MLStjp16pIy4pXotkOC2j56HhX7u7p+fZu35BBHRmr9H3jCPSece4t62dXvGwwzGqstbrGfYe7mteXLLCy1NaH3ZLbPI2DRw7bSM+X9OWCl6QVuo9U9KTpV61EYW67B8eVpGy7XdWFJr55FM4nvZ+s9YW9tBkzp8SeCBiq2yOA5ModLsGp7uQYvN9AA5S0iCe6HjVUm54cw2WfhE7HUvVAdwZlr7BUIWbTMIrn4xvm3gqXPuOGQfqoAvf07sCPWJAAyMNJoU51wVQ9onoA7w="
branches:
  only:
  - master
  - develop
cache:
  directories:
    - "node_modules"